name: "Issue Labeler"
on:
  issues:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v2
      with:
        configuration-path: .github/labeler.yml
        enableVersionedRegex: 0